/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as ContentRouteImport } from './routes/content'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as SupportRouteImport } from './routes/support'
import { Route as UsersRouteImport } from './routes/users'
import { Route as DesignersIdRouteImport } from './routes/designers.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignersIdRoute = DesignersIdRouteImport.update({
  id: '/designers/$id',
  path: '/designers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/content': typeof ContentRoute
  '/orders': typeof OrdersRoute
  '/revenue': typeof RevenueRoute
  '/support': typeof SupportRoute
  '/users': typeof UsersRoute
  '/designers/$id': typeof DesignersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/content': typeof ContentRoute
  '/orders': typeof OrdersRoute
  '/revenue': typeof RevenueRoute
  '/support': typeof SupportRoute
  '/users': typeof UsersRoute
  '/designers/$id': typeof DesignersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/content': typeof ContentRoute
  '/orders': typeof OrdersRoute
  '/revenue': typeof RevenueRoute
  '/support': typeof SupportRoute
  '/users': typeof UsersRoute
  '/designers/$id': typeof DesignersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/content'
    | '/orders'
    | '/revenue'
    | '/support'
    | '/users'
    | '/designers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/content'
    | '/orders'
    | '/revenue'
    | '/support'
    | '/users'
    | '/designers/$id'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/content'
    | '/orders'
    | '/revenue'
    | '/support'
    | '/users'
    | '/designers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  ContentRoute: typeof ContentRoute
  OrdersRoute: typeof OrdersRoute
  RevenueRoute: typeof RevenueRoute
  SupportRoute: typeof SupportRoute
  UsersRoute: typeof UsersRoute
  DesignersIdRoute: typeof DesignersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designers/$id': {
      id: '/designers/$id'
      path: '/designers/$id'
      fullPath: '/designers/$id'
      preLoaderRoute: typeof DesignersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  ContentRoute: ContentRoute,
  OrdersRoute: OrdersRoute,
  RevenueRoute: RevenueRoute,
  SupportRoute: SupportRoute,
  UsersRoute: UsersRoute,
  DesignersIdRoute: DesignersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
